language: php
dist: focal
php:
  - '8.1.0'
env:
  - DB_NAME=test DB_USER=travis DB_PASS= DB_HOST=127.0.0.1 XDEBUG_MODE=coverage
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'
install:
  - composer install --no-interaction
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit src/test/TivinsTest --coverage-clover build/logs/clover.xml
after_success:
  - travis_retry php vendor/bin/php-coveralls
